# https://github.com/probberechts/hexo-theme-cactus
colorscheme: dark
nav:
  Home: /
  About: /about/
  Blog: /archives/
rss:

social_links:
  - icon: github
    link: https://github.com/oatsoda
  - icon: twitter
    label: "@oatsoda"
    link: https://twitter.com/oatsoda
  - icon: linkedin
    link: https://www.linkedin.com/in/ajmilne/

copyright:
  start_year: 2020
  end_year:
