# https://github.com/probberechts/hexo-theme-cactus/blob/master/_config.yml
colorscheme: dark
nav:
  Home: /
  About: /about/
  Blog: /archives/
rss:

social_links:
  - icon: github
    link: https://github.com/oatsoda
  - icon: twitter
    label: "@oatsoda"
    link: https://twitter.com/oatsoda
  - icon: linkedin
    link: https://www.linkedin.com/in/ajmilne/

projects_url: https://github.com/oatsoda

copyright:
  start_year: 2020
  end_year:

tags_overview: true

logo:
  enabled: true
  width: 50
  height: 50
  url: /images/logo.jpg
  gravatar: false
  grayout: true

# filename can't match theme default else gets overwritten
favicon:
  desktop:
    url: /images/icon.ico
    gravatar: false
  # TODO: Need a bigger icon for mobile (192x192 Android, 180x180 Apple)
  android:
    url: /images/icon.ico
    gravatar: false
  apple:
    url: /images/icon.ico
    gravatar: false

google_analytics:
  enabled: true
  id: "G-QS9KGLB7E6"
